image: node:10.5.0
stages:
  - build
  - test
  - deploy
before_script:
  - npm install

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

build-production:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test

deploy-production:
  stage: deploy
  environment:
    name: production
    url: https://h-vuttr.netlify.com
  only:
    - master
  script:    
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod